# Generated by Django 2.0 on 2018-01-05 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=59, verbose_name='商品名称')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='商品价格')),
                ('logic_fee', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='运费')),
                ('pic', models.CharField(blank=True, max_length=199, null=True, verbose_name='图片')),
                ('buy_user', models.SmallIntegerField(default=0, verbose_name='已购买人数')),
                ('level', models.SmallIntegerField(choices=[(0, '不推荐'), (1, '推荐')], default=0, verbose_name='重点推荐')),
                ('content', models.CharField(blank=True, max_length=299, null=True, verbose_name='商品详情')),
                ('inventory', models.BigIntegerField(default=0, verbose_name='库存')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'product',
                'ordering': ['-id'],
                'verbose_name': '疯购商品信息表',
            },
        ),
        migrations.CreateModel(
            name='ProductPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.CharField(max_length=199, verbose_name='图片')),
                ('is_default', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否默认')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=True, related_name='pp_create_user', to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
                ('product', models.ForeignKey(blank=True, null=None, on_delete=True, related_name='pp_product', to='fenggou.Product', verbose_name='商品')),
            ],
            options={
                'db_table': 'product_pic',
                'ordering': ['id'],
                'verbose_name': '商品图片信息',
            },
        ),
        migrations.CreateModel(
            name='ProductScroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=199, verbose_name='商品描述')),
                ('pic', models.CharField(blank=True, max_length=199, null=True, verbose_name='图片')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=True, related_name='psc_product', to='fenggou.Product', verbose_name='商品')),
            ],
            options={
                'db_table': 'product_scroll',
                'ordering': ['-id'],
                'verbose_name': '疯商品轮播图信息',
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=199, verbose_name='商品规格')),
                ('is_default', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=1, verbose_name='是否默认')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='商品价格')),
                ('inventory', models.BigIntegerField(default=0, verbose_name='库存')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=True, related_name='ps_product', to='fenggou.Product', verbose_name='商品')),
            ],
            options={
                'db_table': 'product_spec',
                'ordering': ['-id'],
                'verbose_name': '商品属性表',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=19, unique=True, verbose_name='商品类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent_type', models.ForeignKey(blank=True, null=True, on_delete=True, related_name='pt_parent_type', to='fenggou.ProductType', verbose_name='上级类型')),
            ],
            options={
                'db_table': 'product_type',
                'ordering': ['id'],
                'verbose_name': '疯购商品类型表',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, related_name='pro_name', to='fenggou.ProductType', verbose_name='商品类型'),
        ),
    ]
