# Generated by Django 2.0 on 2018-01-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180105_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersprofile',
            options={'ordering': ['-id'], 'verbose_name': '用户资料表', 'verbose_name_plural': '用户信息列表'},
        ),
        migrations.RemoveField(
            model_name='usersprofile',
            name='nick_name',
        ),
        migrations.RemoveField(
            model_name='usersprofile',
            name='user_name',
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='用户登录账号'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
